# Generated by Django 2.2.4 on 2020-10-12 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap_base', '0005_sisparametrosconfig'),
        
    ]

    operations = [
        migrations.CreateModel(
            name='TrmTramites',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('secuencia', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('archivos', models.TextField(blank=True, null=True)),
                ('ap_aprobador', models.BooleanField(null=True)),
                ('ap_revisor', models.BooleanField(null=True)),
                ('estado_tramite', models.CharField(choices=[('B', 'BORRADOR'), ('T', 'EN TRAMITE'), ('A', 'APROBADO PARA IMPRIMIR'), ('I', 'IMPRESO'), ('D', 'DEVUELTO')], max_length=20, null=True)),
                ('tipo_tramite', models.CharField(choices=[('PARMA', 'PARMA'), ('PERMISO_PESCA', 'PERMISO PESCA')], max_length=20, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1, null=True)),
                ('eliminado', models.BooleanField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_ingreso', models.TextField()),
                ('usuario_ultima_modificacion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('observaciones_dba', models.TextField(blank=True, null=True)),
                ('isla_tramite', models.ForeignKey(blank=True, db_column='isla_tramite', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trm_isla_tramite', to='ap_base.GeoIsla')),
                ('isla_usuario_ingreso_id', models.ForeignKey(blank=True, db_column='isla_usuario_ingreso_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ap_base.GeoIsla')),
                ('per_solicitante_id', models.ForeignKey(blank=True, db_column='per_solicitante_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='per_solicitante_id', to='ap_base.PerPersona')),
            ],
            options={
                'db_table': '"master"."trm_tramites"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrmTramitesDetalles',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fecha_observacion', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado_tramite', models.CharField(choices=[('B', 'BORRADOR'), ('T', 'EN TRAMITE'), ('A', 'APROBADO PARA IMPRIMIR'), ('I', 'IMPRESO'), ('D', 'DEVUELTO')], max_length=20, null=True)),
                ('tipo_tramite', models.CharField(choices=[('PARMA', 'PARMA'), ('PERMISO_PESCA', 'PERMISO PESCA')], max_length=20, null=True)),
                ('estado', models.CharField(max_length=1, null=True)),
                ('eliminado', models.BooleanField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_ingreso', models.TextField()),
                ('usuario_ultima_modificacion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('observaciones_dba', models.TextField(blank=True, null=True)),
                ('isla_usuario_ingreso_id', models.ForeignKey(blank=True, db_column='isla_usuario_ingreso_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ap_base.GeoIsla')),
                ('per_persona_id', models.ForeignKey(blank=True, db_column='per_persona_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trm_tramite_persona_id', to='ap_base.PerPersona')),
                ('trm_tramites_id', models.ForeignKey(blank=True, db_column='trm_tramites_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trm_tramites', to='ap_usuarioexterno.TrmTramites')),
            ],
            options={
                'db_table': '"master"."trm_tramites_detalles"',
                'managed': True,
            },
        ),
    ]
