# Generated by Django 2.2.4 on 2020-10-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap_cuso_controlinsular', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cincontrolaeropuertoiguanas',
            name='sitio_id',
        ),
    ]
