# Generated by Django 2.2.4 on 2020-06-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_daf_certificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dafcertificaciones',
            name='tipo_revision',
            field=models.CharField(choices=[('M', 'MANTENIMIENTO'), ('O', 'OBRA CIVIL'), ('T', 'TIC'), ('N', 'NINGUNO')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldafcertificaciones',
            name='tipo_revision',
            field=models.CharField(choices=[('M', 'MANTENIMIENTO'), ('O', 'OBRA CIVIL'), ('T', 'TIC'), ('N', 'NINGUNO')], max_length=2, null=True),
        ),
    ]
