# Generated by Django 2.2.4 on 2020-06-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_daf_certificaciones', '0002_auto_20200603_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dafcertificaciones',
            name='aprobar_bodega',
        ),
        migrations.RemoveField(
            model_name='historicaldafcertificaciones',
            name='aprobar_bodega',
        ),
        migrations.AlterField(
            model_name='dafcertificaciones',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldafcertificaciones',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
