# Generated by Django 2.2.4 on 2020-08-27 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap_daf_certificaciones', '0004_auto_20200706_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dafcertificaciones',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dafcertificacionesdetalles',
            name='daf_certificaciones_id',
            field=models.ForeignKey(blank=True, db_column='daf_certificaciones_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='det_certificaciones', to='ap_daf_certificaciones.DafCertificaciones'),
        ),
        migrations.AlterField(
            model_name='historicaldafcertificaciones',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
    ]
