from .url_auth import *
from .url_daf import *
from .url_geo import *
from .url_gth import *
from .url_org import *
from .url_per import *
from .url_sis import *
from .url_spn import *
from .url_spt import *
from .url_cuem import *
from .url_bsa import *
from .url_lic import *
from .url_pat import *
from .url_tpr import *
from .url_cin import *
from .url_cuso import *
from .url_spi import *
