# Generated by Django 2.2.4 on 2020-09-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_serv_ambientales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmvEspeciesCantidades',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('lib_entero', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('ind_entero', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('lib_colas_filetes', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('ind_colas_filetes', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('ind_entero_or_lb_colas', models.CharField(blank=True, max_length=5, null=True)),
                ('bloquear_cant_vacias', models.CharField(blank=True, max_length=5, null=True)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario_ingreso', models.TextField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('usuario_ultima_modificacion', models.TextField(blank=True, null=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
                ('isla_usuario_ingreso_id', models.UUIDField(blank=True, null=True)),
                ('eliminado', models.BooleanField(blank=True, null=True)),
                ('periodo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gmv_especies_cantidades',
                'managed': False,
            },
        ),
    ]
