# Generated by Django 2.2.4 on 2020-10-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap_serv_ambientales', '0002_gmvespeciescantidades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GmvEspeciesCantidades',
        ),
        migrations.RemoveField(
            model_name='bsainformecampo',
            name='transporte',
        ),
        migrations.AddField(
            model_name='bsainformecampo',
            name='periodo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bsainformecampo',
            name='transporte_id',
            field=models.ForeignKey(blank=True, db_column='transporte_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ap_serv_ambientales.TrpVehiculo'),
        ),
    ]
