"""
Django settings for dpng project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
from django.utils.translation import ugettext_lazy as _
import os,time,datetime


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6d8b!)%68(bacbo$&nlje_2av_hsqs(nn^85ev@nnifj$4b433'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100


}

JWT_AUTH = { 
    'JWT_AUTH_HEADER_PREFIX': 'PNG',
    'JWT_ALGORITHM': 'HS256',
    'JWT_ALLOW_REFRESH': True,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=100000), # Tiempo de vida de un token
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=1), # Tiempo maximo que puede ser refrescado un token
    #'JWT_VERIFY_EXPIRATION': False
}

PRIVATE_API = '36fda24fe5588fa4285ac6c6c2fdfbdb6b6bc9834699774c9bf777f706d05a88'

LOGIN_REDIRECT_URL='index'
LOGOUT_REDIRECT_URL = 'index'

# Django Site
SITE_ID = 1


# Application definition

INSTALLED_APPS = [
    # Admin Material Design
    'jet.dashboard',
    'jet',

    # Historic Records
    'simple_history',

    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Rest
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'allauth',
    'allauth.account',
    'rest_auth.registration',
    'django_filters',

    # Celery
    'django_celery_results',
    'django_extensions',
    'djcelery_email',

    #Session
    'session_security',

    #Custom APP
    'ap_base',
    'ap_talentohumano',
    'ap_especiesnativas',
    'ap_api',
    'ap_soportetic',
    'ap_adminsys',
    'ap_daf_certificaciones',
    'ap_serv_ambientales',
    'ap_cuem_manejopesquero',
    'ap_cuso_controlmarino',
    'ap_cuso_controlinsular',
    'ap_dup_guias',
    'ap_dup_operacionturistica',
    'ap_especiesintroducidas',
    'ap_usuarioexterno',



    # AMANDA
    # custom apps
    #'ap_galapagos_scheduling.core',
    #'ap_galapagos_scheduling.operador',
    #'ap_galapagos_scheduling.reserva',
    #'ap_galapagos_scheduling.sitio',
    #'ap_galapagos_scheduling.turista',
    #'ap_galapagos_scheduling.guia',

    #'extra_views',
    #'import_export',

    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    'session_security.middleware.SessionSecurityMiddleware',

]

SECURE_SSL_REDIRECT = False

# django-session-timeout 
SESSION_EXPIRE_SECONDS = 6000 #minutos
#SESSION_EXPIRE_SECONDS = 20 #minutos
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_EXPIRE_AFTER_LAST_ACTIVITY_GRACE_PERIOD = 60 # group by minute
SESSION_EXPIRE_AT_BROWSER_CLOSE=True


ROOT_URLCONF = 'dpng.urls'
LOGIN_URL='login'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR + '/ap_base/templates/base/',
            BASE_DIR + '/ap_talentohumano/templates/configuracion/',
            BASE_DIR + '/ap_especiesnativas/templates/especiesnativas/',
            BASE_DIR + '/ap_especiesnativas/templates/configuracion/',
            BASE_DIR + '/ap_adminsys/templates/adminsys/',
            BASE_DIR + '/ap_daf_certificaciones/templates/daf_certificaciones/',
            BASE_DIR + '/ap_especiesintroducidas/templates/ap_especiesintro/',
            BASE_DIR + '/ap_especiesintroducidas/templates/configuracion/',
            #BASE_DIR + '/ap_serv_ambientales/templates/serv_ambientales/',
            #BASE_DIR + '/ap_soportetic/templates/equipos/',

            BASE_DIR + '/ap_celery/templates/emails/',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATES_LOADERS = (
    "admin_tools.template_loaders.Loader",
)

WSGI_APPLICATION = 'dpng.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql', 
        'OPTIONS': {
            'options': '-c search_path=django,master,public,sia,audit'
        },
        'NAME': 'galapagos_db',                            
        'USER': 'postgres',  
        'HOST': '127.0.0.1',                            
        'PASSWORD': '******',                 
        'PORT': '5432',                           
    }
}

IMPORT_EXPORT_USE_TRANSACTIONS = True
#AUTH_USER_MODEL = 'ap_galapagos_scheduling.core.User'

#DATABASE_ROUTERS = ['ap_base.routers.SiaMasterRouter','ap_base.routers.SiaPublicRouter',]
#DATABASE_APPS_MAPPING = {'sia_master': 'sia_master_db'}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es-ec'
TIME_ZONE = 'America/Costa_Rica'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

#STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATICFILES_DIRS = (
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
    'static',
    'media',
    ("dir_media", os.path.join(BASE_DIR, "media")),
    os.path.join(BASE_DIR, "static/media/talentohumano/carnetizacion")

)


############## VARIABLES GLOBALES DPNG ##############################

UPLOAD_PATH = 'images/uploads/' + time.strftime("%Y/%m/%d/")
FILE_UPLOAD_PERMISSIONS = 0o644

#CONFIG BASIC API
API_IP_SERVER = '172.17.151.144:8000'
API_VERSION = 'api/v1'
CODE_VERSION = '2' # Versionamiento de

#CONFIG API DREAMFACTORY
DF_URL = 'http://api.galapagos.gob.ec/api/v2/sysid'
DF_API_KEY = '28d8d89a875cfeb8b7be2f33e6ea8ea1b14061e8f2d4efa77be20136ea5bd96b'
DF_ACCESS_TOKEN = 'Qpa4NL1Ec1T43uCrgDrWLeua2wXd7G'

#CONFIG DIAS RESTANTES PARA LISTAS DE LOS FORMULARIOS PARA ALERTAS
ALERTA_RANGO_DIAS = 10

#RUTA DE ARCHIVOS DE UATH
#FOTOS_CARNET = "./media/talentohumano/carnetizacion/"

# Celery base setup
CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Correo
DEFAULT_FROM_EMAIL = 'sistema.sia@galapagos.gob.ec'
EMAIL_HOST = 'mail.galapagos.gob.ec'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'sistema.sia'
EMAIL_HOST_PASSWORD = 'SystemaS1A.Dj'
EMAIL_USE_TLS = True # TLS settings
EMAIL_BACKEND = 'djcelery_email.backends.CeleryEmailBackend'

#APPEND_SLASH=False

