# Generated by Django 2.2.4 on 2020-10-02 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap_base', '0004_perturista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ap_talentohumano', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerPersonaAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_id', models.ForeignKey(blank=True, db_column='persona_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='auth_persona_id', to='ap_base.PerPersona')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_persona_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"master"."per_persona_auth"',
                'managed': True,
            },
        ),
    ]
