# Generated by Django 2.2.4 on 2020-10-13 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap_talentohumano', '0002_perpersonaauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperfuncionarioaccionpersonal',
            name='nuevo_cargo_distributivo_id',
            field=models.ForeignKey(blank=True, db_column='nuevo_cargo_distributivo_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ap_talentohumano.GthCargoInstitucional'),
        ),
        migrations.AddField(
            model_name='perfuncionarioaccionpersonal',
            name='nuevo_cargo_distributivo_id',
            field=models.ForeignKey(blank=True, db_column='nuevo_cargo_distributivo_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nuevo_cargo_distributivo_id', to='ap_talentohumano.GthCargoInstitucional'),
        ),
    ]
