# Generated by Django 2.2.4 on 2020-06-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sissecuencia',
            name='prefijo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
