# Generated by Django 2.2.4 on 2020-08-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_base', '0003_orgcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerTurista',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tipo_persona', models.CharField(max_length=1)),
                ('tipo_identificacion', models.CharField(blank=True, max_length=1, null=True)),
                ('identificacion', models.CharField(blank=True, max_length=32, null=True)),
                ('nombres', models.TextField(blank=True, null=True)),
                ('apellidos', models.TextField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad_nacimiento_id', models.UUIDField(blank=True, null=True)),
                ('formacion_academica', models.TextField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=1, null=True)),
                ('tipo_sangre', models.TextField(blank=True, null=True)),
                ('lugar_nacimiento', models.TextField(blank=True, null=True)),
                ('nivel_escolaridad', models.TextField(blank=True, null=True)),
                ('pais_nacimiento_id', models.UUIDField(blank=True, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('nombre_completo', models.TextField(blank=True, null=True)),
                ('pais_residencia_id', models.UUIDField(blank=True, null=True)),
                ('provincia_residencia_id', models.UUIDField(blank=True, null=True)),
                ('ciudad_residencia_id', models.UUIDField(blank=True, null=True)),
                ('eliminado', models.BooleanField(blank=True, null=True)),
                ('codigo_postal', models.TextField(blank=True, null=True)),
                ('tratamiento_protocolario', models.CharField(blank=True, max_length=5, null=True)),
                ('migrar', models.BooleanField()),
                ('instruccion_academica', models.TextField(blank=True, null=True)),
                ('tmp_pais_iso2', models.TextField(blank=True, null=True)),
                ('prev_id', models.IntegerField(blank=True, null=True)),
                ('grado_academico', models.TextField(blank=True, null=True)),
                ('residentes_temporales', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
                ('usuario_ingreso', models.TextField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('usuario_ultima_modificacion', models.TextField(blank=True, null=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('observaciones_dba', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"master"."per_turista"',
                'managed': False,
            },
        ),
    ]
