# Generated by Django 2.2.4 on 2020-09-28 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap_base', '0004_perturista'),
    ]

    operations = [
        migrations.CreateModel(
            name='SisParametrosConfig',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('categoria', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('valor', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
                ('eliminado', models.BooleanField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_ingreso', models.TextField()),
                ('usuario_ultima_modificacion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('observaciones_dba', models.TextField(blank=True, null=True)),
                ('isla_usuario_ingreso_id', models.ForeignKey(blank=True, db_column='isla_usuario_ingreso_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ap_base.GeoIsla')),
            ],
            options={
                'db_table': '"master"."sis_parametros_config"',
                'managed': True,
            },
        ),
    ]
