from django.urls import path
from . import views

urlpatterns = [
	path('equipos/',views.sptEquiposList, name='equipos'),
	path('solserv/',views.sptSolicitudServicioList, name='solserv'),
	path('infobajas/',views.spInfoBajasList, name='infobajas'),
	path('data_subtipoProblemaParam/',views.data_subtipoProblemaParam, name='data_subtipoProblemaParam'),
	path('marcas/',views.sptMarcasList, name='marcas'),
	path('preguntas/',views.sptPreguntasList, name='preguntas'),
	path('ubicaciones/',views.sptUbicacionList, name='ubicaciones'),
	path('productos/',views.sptProductoList, name='productos'),
	path('tipoequipo/',views.sptTipoEquipoList, name='tipoequipo'),
	path('unidadmedida/',views.sptUnidadMedidaList, name='unidadmedida'),
	path('equipo_data/',views.equipo_data, name='equipo_data'),
	path('data_equipoParam/',views.data_equipoParam, name='data_equipoParam'),
	path('marca_data/',views.marca_data, name='marca_data'),
	path('data_marcasParam/',views.data_marcasParam, name='data_marcasParam'),
	path('ubicacion_data/',views.ubicacion_data, name='ubicacion_data'),
	path('data_ubicacionesParam/',views.data_ubicacionesParam, name='data_ubicacionesParam'),
	path('producto_data/',views.producto_data, name='producto_data'),
	path('data_ProductoParam/',views.data_ProductoParam, name='data_ProductoParam'),
	path('tipoequipo_data/',views.tipoequipo_data, name='tipoequipo_data'),
	path('data_tipoequipoParam/',views.data_tipoequipoParam, name='data_tipoequipoParam'),
	path('unidadmedida_data/',views.unidadmedida_data, name='unidadmedida_data'),
	path('data_unidadmedidaParam/',views.data_unidadmedidaParam, name='data_unidadmedidaParam'),	
	path('get_remote_data_sysaid/',views.get_remote_data_sysaid, name='get_remote_data_sysaid'),
	path('solserv_data/',views.solserv_data, name='solserv_data'),
	path('data_solservParam/',views.data_solservParam, name='data_solservParam'),
	path('data_infoBajaCabParam/',views.data_infoBajaCabParam, name='data_infoBajaCabParam'),
	path('data_infoBajaCab/',views.data_infoBajaCab, name='data_infoBajaCab'),
	path('data_secinfoBajaCab/',views.data_secinfoBajaCab, name='data_secinfoBajaCab'),
	path('data_equipoCustParam/',views.data_equipoCustParam, name='data_equipoCustParam'),
	path('pregunta_data/',views.pregunta_data, name='pregunta_data'),
	path('data_preguntasParam/',views.data_preguntasParam, name='data_preguntasParam'),
	path('import_product/',views.import_product, name='import_product'),
	path('update_data_remote/',views.update_data_remote, name='update_data_remote'),
	#path('upload_filesEq_json/',views.upload_filesEq_json, name='upload_filesEq_json'),
	path('datasecuencia_SolicitudServicio/',views.datasecuencia_SolicitudServicio, name='datasecuencia_SolicitudServicio'),
]