from django.urls import path
from . import views


urlpatterns = [
    #configuracion
    path('dashboard/', views.dashboard, name='dashboard'),
    path('reporteAvistamientos/', views.reporteAvistamientos, name='reporteAvistamientos'),
    path('reportePetreles/', views.reportePetreles, name='reportePetreles'),
    path('centrosCrianza/', views.centrosCrianza, name='centrosCrianza'),
    path('poblacion/', views.poblacion, name='poblacion'),
    path('sitios/', views.sitios, name='sitios'),
    path('nidos/', views.nidos, name='nidos'),
    path('especies/', views.especies, name='especies'),
    path('tortugasAdultas/', views.tortugasAdultas, name='tortugasAdultas'),
    path('tortugasNidos/', views.tortugasNidos, name='tortugasNidos'),
    path('petrelesNidos/', views.petrelesNidos, name='petrelesNidos'),
    path('flamingosNidos/', views.flamingosNidos, name='flamingosNidos'),
    path('control/', views.control, name='control'),
    path('control_crecimiento/', views.control_crecimiento, name='control_crecimiento'),
    path('control_crecimiento_encontrados/', views.control_crecimiento_encontrados, name='control_crecimiento_encontrados'),
    path('ver_control_crecimiento/', views.ver_control_crecimiento, name='ver_control_crecimiento'),
    path('buscar_pintura/', views.buscar_pintura, name='buscar_pintura'),
    path('reporte_control_crecimiento/', views.reporte_control_crecimiento, name='reporte_control_crecimiento'),
    path('reporte_grupo/', views.reporte_grupo, name='reporte_grupo'),
    path('data_ControlHuevos/', views.data_ControlHuevos, name='data_ControlHuevos'),
    path('data_medicionesParam/', views.data_medicionesParam, name='data_medicionesParam'),
 	path('dataCabmedicionesParam/', views.dataCabmedicionesParam, name='dataCabmedicionesParam'),
 	path('data_ultimaMedicionParam/', views.data_ultimaMedicionParam, name='data_ultimaMedicionParam'),
 	path('datos_huevopintura/', views.datos_huevopintura, name='datos_huevopintura'),
 	path('data_controlcreceParam/', views.data_controlcreceParam, name='data_controlcreceParam'),
 	path('data_huevosCentroCrianza/', views.data_huevosCentroCrianza, name='data_huevosCentroCrianzas'),
 	path('data_huevosCentroCrianzaDetalles/', views.data_huevosCentroCrianzaDetalles, name='data_huevosCentroCrianzaDetalles'),
 	path('data_huevosCentroCrianzaPeriodoDetalles/', views.data_huevosCentroCrianzaPeriodoDetalles, name='data_huevosCentroCrianzaPeriodoDetalles'),
 	path('data_detalleControlCrecimiento/', views.data_detalleControlCrecimiento, name='data_detalleControlCrecimiento'),
    path('editCentroCrianza/', views.editCentroCrianza, name='editCentroCrianza'),
    path('editPoblacion/', views.editPoblacion, name='editPoblacion'),
    path('editTortugasAdultas/', views.editTortugasAdultas, name='editTortugasAdultas'),
    path('dataTortugasAdultas/', views.dataTortugasAdultas, name='dataTortugasAdultas'),
    path('estadoActual/', views.estadoActual, name='estadoActual'),
    path('data_estadoActualCC/', views.data_estadoActualCC, name='data_estadoActualCC'),
    path('editTortugasNido/', views.editTortugasNido, name='editTortugasNido'),
    path('editPetrelesNido/', views.editPetrelesNido, name='editPetrelesNido'),
    path('editNido/', views.editNido, name='editNido'),
    path('editFla/', views.editFla, name='editFla'),
    path('data_observAves/', views.data_observAves, name='data_observAves'),
    path('data_observOtrasEsp/', views.data_observOtrasEsp, name='data_observOtrasEsp'),
    path('data_datosNidos/', views.data_datosNidos, name='data_datosNidos'),
    path('data_observFla/', views.data_observFla, name='data_observFla'),
    path('data_ParamTorNido/', views.data_ParamTorNido, name='data_ParamTorNido'),
    path('data_ParamPet/', views.data_ParamPet, name='data_ParamPet'),
    path('data_ParamFla/', views.data_ParamFla, name='data_ParamFla'),
    path('editEspecies/', views.editEspecies, name='editEspecies'),
    path('update_General_mediciones', views.update_General_mediciones, name='update_General_mediciones'),
    path('insert_General_mediciones', views.insert_General_mediciones, name='insert_General_mediciones'),
    path('data_ParamNido/', views.data_ParamNido, name='data_ParamNido'),

]